//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadowVerse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follower
    {
        public int id { get; set; }
        public string story { get; set; }
        public string imgUrl { get; set; }
        public Nullable<byte> attack { get; set; }
        public Nullable<byte> defense { get; set; }
        public string ability { get; set; }
        public string onslaught { get; set; }
        public string ward { get; set; }
        public string bane { get; set; }
        public string enhance { get; set; }
        public string fanfare { get; set; }
        public string lastWords { get; set; }
        public string trait { get; set; }
    }
}
