//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadowVerse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShadowVerseEntities : DbContext
    {
        public ShadowVerseEntities()
            : base("name=ShadowVerseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amulet> Amulet { get; set; }
        public virtual DbSet<cardCharm> cardCharm { get; set; }
        public virtual DbSet<cardList> cardList { get; set; }
        public virtual DbSet<cardSet> cardSet { get; set; }
        public virtual DbSet<cardSetData> cardSetData { get; set; }
        public virtual DbSet<enhance> enhance { get; set; }
        public virtual DbSet<Evolved> Evolved { get; set; }
        public virtual DbSet<Follower> Follower { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<Spell> Spell { get; set; }
    }
}
